name: Deploy static Nuxt site to GH-Pages

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:

  build:
    name: ==> BUILD STATIC SITE <==
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: == 1/6 == Checkout ========================================
        uses: actions/checkout@v6

      - name: == 2/6 == Install pnpm ====================================
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false

      - name: == 3/6 == Setup Node v24 ==================================
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: pnpm

      - name: == 4/6 == Install dependencies ============================
        run: pnpm install --frozen-lockfile

      - name: == 5/6 == Generate static site (HTML export) with Nuxt ====
        run: |
          echo "NUXT_APP_BASE_URL: $NUXT_APP_BASE_URL."
          pnpm run generate
        env:
          NUXT_APP_BASE_URL: ${{vars.NUXT_APP_BASE_URL}}

      - name: == 6/6 == Upload artifact =================================
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public

  deploy:
    name: ==> DEPLOY STATIC SITE <==
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: == 1/1 == Deploy to GitHub Pages ==========================
        id: deployment
        uses: actions/deploy-pages@v4
